[build]
  command = "cd .. && cd tubeheadlines-admin && npm install && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=./"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
